# Generated by Django 5.2.17 on 2026-08-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
    ]
